### ISSUE TITLE
大佬，数据包签名问题怎么解决

### ISSUE THREAD

**Issue by zhongjiao01** [CTF-MissFeng/jsForward#1]
如果遇到敏感字段加密，然后对应关键字段再进行签名，也就说有两套加密算法，这种情况怎么破呢

**Comment by CTF-MissFeng** [comment]
> 如果遇到好奇的挖掘，然后对应的关键字段再进行个性化，示范说有两套智能算法，这种情况怎么破呢

这个没多大关系，有几层加密，就相应添加发送就行了，始终是最先执行的函数触发
